# Generated by Django 2.2.3 on 2020-03-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duenio',
            fields=[
                ('idDuenios', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Duenio',
                'verbose_name_plural': 'Duenios',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('nombre', models.CharField(help_text='Ingresar nombre del negocio', max_length=50)),
                ('direccion', models.CharField(help_text='Ingresar la direccion del negocio', max_length=200)),
                ('cupoClientes', models.PositiveIntegerField(help_text='Ingresar el máximo de clientes que pueden ingresar')),
                ('intervalosMinutos', models.PositiveIntegerField(help_text='Ingresar el intervalo entre tandas de clientes')),
                ('horaRestringidaInicio', models.TimeField()),
                ('horaRestringidaFin', models.TimeField()),
                ('justificativoHoraRestringida', models.CharField(help_text='Ingresar el justificativo', max_length=200)),
                ('latitud', models.CharField(help_text='Ingresar la latitud del negocio', max_length=50)),
                ('longitud', models.CharField(help_text='Ingresar la longitud del negocio', max_length=50)),
                ('idNegocio', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('isPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingresar la descripcion del perfil', max_length=50)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('idRubro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingresar la descripcion del rubro', max_length=100)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('idSexo', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(help_text='Ingresar el sexo', max_length=50)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(help_text='Ingresar el nombre del usuario', max_length=50)),
                ('userPassword', models.CharField(help_text='Ingresar la contraseña del usuario', max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingresar su nombre', max_length=50)),
                ('dni', models.PositiveIntegerField(help_text='Ingresar su DNI')),
                ('direccion', models.CharField(help_text='Ingresar la direccion', max_length=200)),
                ('latitud', models.CharField(help_text='Ingresar la latitud', max_length=50)),
                ('longitud', models.CharField(help_text='Ingresar la longitud', max_length=50)),
                ('sexo', models.ForeignKey(help_text='Elija el sexo', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Sexo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('idPerfilUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('idPerfil', models.ForeignKey(help_text='Elija el perfil', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Perfil')),
                ('idUsuario', models.ForeignKey(help_text='Elija el usuario', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='NegocioRubro',
            fields=[
                ('idRubroNegocio', models.AutoField(primary_key=True, serialize=False)),
                ('idNegocio', models.ForeignKey(help_text='Elija el negocio', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Negocio')),
                ('idRubro', models.ForeignKey(help_text='Elija el rubro', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Rubro')),
            ],
            options={
                'verbose_name': 'Rubro de negocio',
                'verbose_name_plural': 'Rubros de negocios',
            },
        ),
        migrations.CreateModel(
            name='NegocioDuenio',
            fields=[
                ('idNegocioDuenio', models.AutoField(primary_key=True, serialize=False)),
                ('idDuenio', models.ForeignKey(help_text='Elija el duenio', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Duenio')),
                ('idNegocio', models.ForeignKey(help_text='Elija el negocio', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Negocio')),
            ],
            options={
                'verbose_name': 'Negocio dueño',
                'verbose_name_plural': 'Negocios dueños',
            },
        ),
        migrations.AddField(
            model_name='duenio',
            name='idPersona',
            field=models.ForeignKey(help_text='Elija la persona', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Persona'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('idPersona', models.ForeignKey(help_text='Elija la persona', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Persona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
