# Generated by Django 2.2.3 on 2020-03-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_turno_seguro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idTurnos', models.AutoField(primary_key=True, serialize=False)),
                ('horarioInicio', models.TimeField()),
                ('horarioFin', models.TimeField()),
                ('idCliente', models.ForeignKey(help_text='Elija el cliente', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Cliente')),
                ('idNegocio', models.ForeignKey(help_text='Elija el negocio', on_delete=django.db.models.deletion.CASCADE, to='mi_turno_seguro.Negocio')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
