# Generated by Django 2.2.3 on 2020-03-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_turno_seguro', '0002_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default=1, help_text='Ingrese el numero de telefono', max_length=20),
            preserve_default=False,
        ),
    ]
